"""Pure decision-layer contracts for the CMRE AI ally.

The contracts deliberately contain summarized, player-visible state rather than Ares objects.
This keeps decision logic replayable and prevents an upper-level policy from issuing raw SC2
orders directly.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any, Mapping


class ActionStatus(str, Enum):
    ACCEPTED = "accepted"
    QUEUED = "queued"
    ISSUED = "issued"
    APPLIED = "applied"
    FAILED = "failed"
    EXPIRED = "expired"
    CANCELLED = "cancelled"


@dataclass(frozen=True)
class MissionSummary:
    """Mission state needed by the policy coordinator."""

    map_name: str = "dead_of_night"
    objective_count: int = 0
    completed_objectives: int = 0
    failed_objectives: int = 0
    night_index: int = 0
    night_active: bool = False
    mission_over: bool = False
    defeat: bool = False

    @property
    def objectives_complete(self) -> bool:
        return (
            self.objective_count > 0
            and self.completed_objectives >= self.objective_count
            and self.failed_objectives == 0
        )


@dataclass(frozen=True)
class AllyObservation:
    """Stable, serializable observation consumed by the decision layer."""

    loop: int
    player_id: int
    minerals: int = 0
    vespene: int = 0
    supply_used: int = 0
    supply_cap: int = 0
    bases: int = 0
    pending_bases: int = 0
    workers: int = 0
    army_supply: float = 0.0
    worker_loss_pct: float = 0.0
    own_units: tuple[Mapping[str, Any], ...] = ()
    visible_enemies: tuple[Mapping[str, Any], ...] = ()
    threatened_bases: int = 0
    low_health_combat_units: int = 0
    mission: MissionSummary = field(default_factory=MissionSummary)

    @property
    def supply_remaining(self) -> int:
        return max(0, self.supply_cap - self.supply_used)

    @property
    def has_base_threat(self) -> bool:
        return self.threatened_bases > 0

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class ActionSpec:
    """Declaration of a decision-layer intent and its execution metadata."""

    name: str
    description: str
    priority: int
    allowed_phases: frozenset[str]
    argument_types: Mapping[str, type] = field(default_factory=dict)
    required_arguments: frozenset[str] = frozenset()
    cooldown_loops: int = 0
    timeout_loops: int = 0
    executor: str = ""


@dataclass(frozen=True)
class DecisionRequest:
    """A high-level intent request generated by the coordinator."""

    action_name: str
    loop: int
    phase: str
    arguments: Mapping[str, Any] = field(default_factory=dict)
    reason: str = ""
    priority_override: int | None = None


@dataclass(frozen=True)
class ActionDecision:
    """Candidate action plus validation outcome."""

    request: DecisionRequest
    accepted: bool
    reason: str
    priority: int


@dataclass(frozen=True)
class ActionResult:
    """Execution acknowledgement kept separate from action acceptance."""

    action_name: str
    request_loop: int
    status: ActionStatus
    loop: int
    reason: str = ""
    executor: str = ""


@dataclass(frozen=True)
class DecisionFrame:
    """One complete policy decision suitable for trace export."""

    loop: int
    phase: str
    observation: AllyObservation
    candidates: tuple[ActionDecision, ...]
    selected: ActionDecision | None
    results: tuple[ActionResult, ...] = ()
