UseData: false
Debug: false
GameStep: 2
DebugGameStep: 2
DebugOptions:
  ActiveGrid: Ground
  ChatDebug: false
  DebugSpawn: false
  ShowPathingCost: false
  ShowBuildingFormation: false
  ResourceDebug: false
Distances:
  FlyingEnemyNearBases: 20.0
  GroundEnemyNearBases: 15.0
  GroundEnemyLeavingBases: 24.0
  FlyingEnemyLeavingBases: 22.0
Features:
  TacticalGroundGrid: false
Building:
  CancelOrder: 18
Mining:
  GeyserDistanceFactor: 1.05
  GeyserThreshold: 0.05
  MineralDistanceFactor: 1.25
  TownhallDistanceFactor: 1.08
Pathing:
  RangeBuffer: 4.0
  EffectsRangeBuffer: 1.0
  CostMultiplier: 1
  Effects: {}
Placement:
  WorkerOnRouteTimeout: 60.0
