#!/usr/bin/env python3
"""从 prestige-bonus-extract.json 生成 GameStrings.txt 本地化文本。

每个 supplement upgrade 输出：
  Upgrade/Name/{bonus_upgrade_id}={display_name} {prestige_name} 优点
  Upgrade/Tooltip/{bonus_upgrade_id}={advantage_text}
"""
import json
from pathlib import Path

EXTRACT_JSON = Path(r"e:\Code\MyMod\SC2VibeTools\sc2-porting-workspace\artifacts\buff-patch\prestige-bonus-extract.json")
OUTPUT = Path(r"e:\Code\MyMod\SC2VibeTools\sc2-porting-workspace\src\projects\cmre-porting\packages\Mods\Commanders\CMRE_BuffPatch.SC2Mod\zhCN.SC2Data\LocalizedData\GameStrings.txt")


def get_bonus_upgrade_id(prestige: dict) -> str:
    if prestige.get("bonus_upgrade_id"):
        return prestige["bonus_upgrade_id"]
    primary = prestige.get("primary_upgrade", "")
    return f"{primary}Bonus" if primary else ""


def main():
    data = json.loads(EXTRACT_JSON.read_text(encoding="utf-8"))
    lines = [
        "// CMRE Buff Patch localizations",
        "// Auto-generated by tools/buff-patch/generate-localizations.py",
        "",
    ]
    count = 0
    for cmd in data.get("commanders", []):
        display = cmd.get("display_name", cmd.get("runtime_commander", ""))
        for p in cmd.get("prestiges", []):
            if p.get("needs_manual_review", False):
                continue
            upgrade_id = get_bonus_upgrade_id(p)
            if not upgrade_id:
                continue
            name = p.get("name", "")
            tip = p.get("advantage_text", "").replace("\n", " ").replace("<n/>", " ")
            # 移除嵌套的颜色标签
            tip = tip.replace("<s val=\"Coop_Prestige_Advantage\">优点</s>", "").strip()
            lines.append(f"Upgrade/Name/{upgrade_id}={display} {name} 优点")
            lines.append(f"Upgrade/Tooltip/{upgrade_id}={tip}")
            # 注释：galaxy_dispatch 提示
            if p.get("galaxy_dispatch_required", False):
                actions = p.get("galaxy_dispatch_actions", [])
                if actions:
                    lines.append(f"// {upgrade_id} 需要 galaxy dispatch:")
                    for action in actions:
                        lines.append(f"//   - {action}")
            lines.append("")
            count += 1

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"[OK] 写入 {count} 个 upgrade 本地化 -> {OUTPUT}")


if __name__ == "__main__":
    main()
